// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = [
    {
      _id: "000000000000000000000003",
      name: "Bill Nye the Science Guy"
    }, {
      _id: "000000000000000000000004",
      name: "Elon Musk"
    }
  ];

}).call(this);
